# This file configures your Cloudflare Pages project
name = "rushes"
compatibility_date = "2024-04-05" # Use a recent date

# This is the line that fixes the error
compatibility_flags = ["nodejs_compat"]
